language : generic
sudo : required
services:
    - docker

before_install:
    - docker build -t jcalarcon/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jcalarcon/react-test npm test -- --coverage

after_success:
    - docker build -t jcalarcon/multi-client ./client 
    - docker build -t jcalarcon/nulti-nginx ./nginx
    - docker build -t jcalarcon/multi-server ./server
    - docker build -t jcalarcon/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push then to docker hub
    - docker push jcalarcon/multi-client
    - docker push jcalarcon/multi-nginx
    - docker push jcalarcon/multi-server
    - docker push jcalarcon/multi-worker