sudo : required
language : generic
services:
    - docker

before_install:
    - docker build -t churon17/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true churon17/react-test npm test -- --coverage

after_success:
    - docker build -t churon17/multi-client ./client 
    - docker build -t churon17/nulti-nginx ./nginx
    - docker build -t churon17/multi-server ./server
    - docker build -t churon17/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push then to docker hub
    - docker push churon17/multi-client
    - docker push churon17/multi-nginx
    - docker push churon17/multi-server
    - docker push churon17/multi-worker